- name: Test VMware collection
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - community.vmware

  vars:
    #vcenter_hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    #vcenter_user: '{{ lookup("env", "VMWARE_USER") }}'
    #vcenter_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    vcenter_hostname: 'vcsnsx-vc.infra.demo.redhat.com'
    vcenter_user: 'sandbox-xdlf9@demo'
    vcenter_password: 'e.lVsWlgQx31'
    datacenter: "SDDC-Datacenter"
    disk_datastore: ""
    vm_name: "test-vm"

  tasks:
    - name: Get vCenter version
      community.vmware.vmware_about_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"      
        validate_certs: false
      register: about

    - name: Show vCenter information
      debug:
        var: about

    - name: Gather current VM disk info
      community.vmware.vmware_guest_disk_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: false
        name: "{{ vm_name }}"
      register: vm_disks

    - name: Normalize disk list
      ansible.builtin.set_fact:
        disk_list: >-
          {{
            (vm_disks.guest_disk_info.values() | list)
            if (vm_disks.guest_disk_info is defined)
            else []
          }}

    - ansible.builtin.debug:
        msg: "{{ disk_list[0].controller_key }}"

    #- name: Show disk summary
    #  ansible.builtin.debug:
    #    msg: "Disk: {{ item.label }} | Datastore: {{ item.backing_datastore }} | Size: {{ item.capacity_in_bytes | int / 1073741824 }} GB"
    #  loop: "{{ disk_list }}"
    


    - name: Extract controller and unit numbers
      ansible.builtin.set_fact:
        used_unit_numbers: "{{ disk_list[0].unit_number }}"
        used_controllers:  "{{ disk_list[0].controller_bus_number | default(0) }}"
    

    - name: Calculate next SCSI controller and unit number
      ansible.builtin.set_fact:
        scsi_controller:   "{{ used_controllers | int  | default(0) }}"
        next_unit_number:  "{{ (used_unit_numbers | sort | last | int) + 1 if used_unit_numbers | length > 0 else 0 }}"
        target_datastore: >-
          {{
            disk_datastore
            if (disk_datastore | length > 0)
            else (disk_list[0].backing_datastore if disk_list | length > 0 else 'undefined')
          }}
        current_disks: "{{ disk_list }}"

    - name: Show detected VM disk summary
      ansible.builtin.debug:
        msg:
          - "Total disks found: {{ current_disks | length }}"
          - "Datastores in use: {{ current_disks | map(attribute='backing_datastore') | list | unique }}"
          - "Next SCSI controller: {{ scsi_controller }}"
          - "Next unit number: {{ next_unit_number }}"
          - "Datastore selected for new disk: {{ target_datastore }}"
